### ISSUE TITLE
Unsound usages of unsafe `transmute` implementation from `usize` to `*mut T`

### ISSUE THREAD

**Issue by llooFlashooll** [zakarumych/allocator-api2#15]
Hi, I am scanning the allocator-api2 in latest version with my own static analyzer tool.

Unsafe conversion found at: src/stable/mod.rs:99:9: 99:35.
``` rust
#[cfg(feature = "alloc")]
#[inline(always)]
fn invalid_mut<T>(addr: usize) -> *mut T {
    #[allow(clippy::useless_transmute, clippy::transmutes_expressible_as_ptr_casts)]
    unsafe {
        core::mem::transmute(addr)
    }
}
```

This unsound implementation would create a misalignment issues if the generics type `T` is not properly handled like other random types.

The problematic value is further manipulated at: src/stable/alloc/system.rs:104:13: 107:15.

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. If we further manipulate the problematic converted types, it would potentially lead to different consequences. I am reporting this issue for your attention.

**Comment by zakarumych** [comment]
Hi!

Thank you for creating this issue.
However to the best of my knowledge this function is safe and sound as it creates potentially unaligned and dangling raw pointer.
And user of the pointer is responsible to ensure its alignment and that it points to memory that can be interpreted as `T`.

**Comment by zakarumych** [comment]
In system.rs a pointer to `u8` is created with additional alignment from the argument when size requested is zero.

This create aligned dangling pointer but it is OK since user must use it only to zero-sized memory access and only alignment is required.
