### ISSUE TITLE
MSRV

### ISSUE THREAD

**Issue by s-arash** [zakarumych/allocator-api2#20]
It'd be good to specify the [MSRV](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) in `Cargo.toml`. The `0.2.19` release of this crate has silently bumped the required Rust version to 1.73 because of its dependence on `NonNull::<T>::as_ref()` being `const fn`, which may not have been entirely intentional given the popularity of this crate.

I'd also suggest having [CI tests](https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-rust-version) to verify the MSRV.

I noticed this issue because [CI started failing](https://github.com/s-arash/ascent/actions/runs/11750267020) on my Rust repository that has an indirect dependency (via `hashbrown`) on this crate.

**Comment by zakarumych** [comment]
This was unintentional.
I'll set MSRV to 1.63 - same as hashbrown.

**Comment by zakarumych** [comment]
I've published new patch version `0.2.20` that is compatible with rust 1.63.
And yanked `0.2.19`

**Comment by s-arash** [comment]
Thanks @zakarumych for the quick fix!
