### ISSUE TITLE
no_std

### ISSUE THREAD

**Issue by duanyu-yu** [zakarumych/allocator-api2#9]
Hi! Is there any option to have a `no_std` version of this crate? 
I'm now building an allocator for our loader of [Hermit](https://github.com/hermit-os), which is `no_std` only. So it would be great if allocator-api2 could also be `no_std`. :)

**Comment by zakarumych** [comment]
Then disable default features and do not enable "std" :)

**Comment by duanyu-yu** [comment]
It works. Thanks! :)
